osx_image: xcode11
language: swift

jobs:
  include:
    # - stage: Lint
    install:
      - wget --output-document /tmp/SwiftLint.pkg https://github.com/realm/SwiftLint/releases/download/0.33.1/SwiftLint.pkg && sudo installer -pkg /tmp/SwiftLint.pkg -target /
    script:
      - swiftlint
      - swift test
      - swift build
      - xcodebuild -workspace ClaretCacheDemo.xcworkspace -scheme ClaretCacheDemo -sdk `xcodebuild -showsdks | grep -Eo "iphonesimulator([0-9]{1,}\.)+[0-9]{1,}"`  build
# stages:
# - Lint
# - Test
